
// This file was auto-generated by ML.NET Model Builder. 

using System;
using static System.Console;

namespace SentimentModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

            WriteLine("\n================ Welcome to the Text Classifier ================");

            while (true)
            {
                Write("\nEnter text to classify (or type 'q' to end program): ");
                string input = ReadLine();
                if (input.ToLower() == "q") break;

                var sampleData = new SentimentModel.ModelInput() { Col0 = input };

                var sortedScoresWithLabel = SentimentModel.PredictAllLabels(sampleData);

                WriteLine(new string('-', 55));
                WriteLine($"Input: '{input}'");
                WriteLine(new string('-', 55));
                WriteLine($"\n{"Class",-20}{"Score",10}");
                WriteLine(new string('-', 31)); // Divider line

                foreach (var score in sortedScoresWithLabel)
                {
                    WriteLine($"{score.Key,-20}{score.Value * 100,10:0.00}%\n");
                }
                WriteLine(new string('-', 55));
                WriteLine();
            }
        }
    }
}
